sudo: required

language: rust
rust:
  - nightly

before_install:
  - sudo apt update && sudo apt install gcc-multilib g++-multilib qemu-system-x86 doxygen python3-sphinx python3-pip -y
  - pip3 install sphinx-rtd-theme
  - cargo install cargo-xbuild
  - rustup component add rust-src

install:
  - make

script:
  - ./test.sh
  - ./docs/build_docs.sh
