[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "i386.json"

[env]
RUSTFLAGS = "-C target-cpu=native -C opt-level=3 -C link-arg=-Wl,--gc-sections"
